name: Feature Request / Improvement
description: Propose a new feature, enhancement, or improvement
title: "[Feature/Improvement]: "
labels:
  - enhancement
body:
  - type: textarea
    id: feature_description
    attributes:
      label: Feature / Improvement Description
      description: Describe the requested feature or improvement.
      value: |
        ### 1. Why is this feature needed?
        

        ### 2. Does any other software provide this? (Optional)
        

        ### 3. Requires Android security/root bypass? (Optional)
        
    validations:
      required: true
