name: Question
description: Ask a question about Android DEX
title: "[Question]: "
labels:
  - question
body:
  - type: textarea
    id: question
    attributes:
      label: Question Details
      description: Ask anything about Android DEX.
      value: |
        > Note: Source code can't be shared so don't ask for code.

        Describe your question here:
        
    validations:
      required: true
